baseURL = "https://andreasbergstrom.com/"
languageCode = "en-us"
title = "Andreas Bergström"
theme = "keepit"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 4

[params]
    since = 2019
    author = "Andreas Bergström"
    avatar = "/images/me/avatar.jpeg"
    subtitle = "Developer"
    cdn_url = ""
    home_mode = "" # post or other

    google_verification = ""

    description = "" # site description
    keywords = "" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.social]
    GitHub = "andreas-bergstrom"
    Linkedin = "andreaserikbergstrom"
    Twitter = "echoandreas"
    Instagram = "andreas_erik_bergstrom"
    Email   = "hi@andreasbergstrom.com"
    Facebook = "andreas.erik.bergstrom"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtube = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    Stackoverflow = "1202214"

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Fastbyte01"

  [params.publisher]
    name = "Fastbyte01"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600
    